/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPolicko.java
 *
 * Created on 15.1.2011, 15:31:44
 */
package ui.aplikace;

import javax.swing.Icon;
import ui.gui.icons.IconLoader;

/**
 *
 * @author notebook
 */
public class PanelPolicko extends javax.swing.JPanel {

    protected Icon kulickaZlata = IconLoader.loadOrangeRing();
    protected Icon kulickaCerna = IconLoader.loadBlackRing();
    protected Icon kulickaBila = IconLoader.loadWhiteRing();
    

    /** Creates new form PanelPolicko */
    public PanelPolicko() {
        initComponents();        
    }    
    
    public void zobrazZlatou(){
        jLabelKulicka.setIcon(kulickaZlata);
    }
    
    public void zobrazCernou(){
        jLabelKulicka.setIcon(kulickaCerna);
    }
    public void zobrazBilou(){
        jLabelKulicka.setIcon(kulickaBila);
    }
    public void zobrazZadnou(){
        jLabelKulicka.setIcon(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelKulicka = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(30, 30));
        setMinimumSize(new java.awt.Dimension(30, 30));
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(jLabelKulicka, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelKulicka;
    // End of variables declaration//GEN-END:variables
}
