/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHra.java
 *
 * Created on 15.1.2011, 15:26:56
 */

package ui.gui.komponenty;

import java.util.ArrayList;
import javax.swing.Icon;
import ui.alg.Hra;
import ui.alg.Policko;

/**
 *
 * @author notebook
 */
public class PanelHra extends javax.swing.JPanel {

    /** Creates new form PanelHra */
    public PanelHra() {
        initComponents();
    }



    public void nastavPanelZeHry(Hra hra){
        panelPolicko1.nastavHodnotuZPolicka(hra.getPolicka().get(0));
        panelPolicko2.nastavHodnotuZPolicka(hra.getPolicka().get(1));
        panelPolicko3.nastavHodnotuZPolicka(hra.getPolicka().get(2));
        panelPolicko4.nastavHodnotuZPolicka(hra.getPolicka().get(3));
        panelPolicko5.nastavHodnotuZPolicka(hra.getPolicka().get(4));
        panelPolicko6.nastavHodnotuZPolicka(hra.getPolicka().get(5));
        panelPolicko7.nastavHodnotuZPolicka(hra.getPolicka().get(6));
        panelPolicko8.nastavHodnotuZPolicka(hra.getPolicka().get(7));
        panelPolicko9.nastavHodnotuZPolicka(hra.getPolicka().get(8));
        panelPolicko10.nastavHodnotuZPolicka(hra.getPolicka().get(9));
        panelPolicko11.nastavHodnotuZPolicka(hra.getPolicka().get(10));
        panelPolicko12.nastavHodnotuZPolicka(hra.getPolicka().get(11));
        panelPolicko13.nastavHodnotuZPolicka(hra.getPolicka().get(12));
        panelPolicko14.nastavHodnotuZPolicka(hra.getPolicka().get(13));
        panelPolicko15.nastavHodnotuZPolicka(hra.getPolicka().get(14));
        panelPolicko16.nastavHodnotuZPolicka(hra.getPolicka().get(15));
        panelPolicko17.nastavHodnotuZPolicka(hra.getPolicka().get(16));
    }


    public void setDefault(){
        panelPolicko1.zobrazCernou();
        panelPolicko2.zobrazZadnou();
        panelPolicko3.zobrazCernou();
        panelPolicko4.zobrazZadnou();
        panelPolicko5.zobrazCernou();
        panelPolicko6.zobrazBilou();
        panelPolicko7.zobrazBilou();
        panelPolicko8.zobrazBilou();
        panelPolicko9.zobrazZlatou();
        panelPolicko10.zobrazBilou();
        panelPolicko11.zobrazBilou();
        panelPolicko12.zobrazBilou();
        panelPolicko13.zobrazCernou();
        panelPolicko14.zobrazZadnou();
        panelPolicko15.zobrazCernou();
        panelPolicko16.zobrazZadnou();
        panelPolicko17.zobrazCernou();       
    }

    public void setFinal(){
        panelPolicko1.zobrazBilou();
        panelPolicko2.zobrazZadnou();
        panelPolicko3.zobrazBilou();
        panelPolicko4.zobrazZadnou();
        panelPolicko5.zobrazBilou();
        panelPolicko6.zobrazCernou();
        panelPolicko7.zobrazCernou();
        panelPolicko8.zobrazCernou();
        panelPolicko9.zobrazZlatou();
        panelPolicko10.zobrazCernou();
        panelPolicko11.zobrazCernou();
        panelPolicko12.zobrazCernou();
        panelPolicko13.zobrazBilou();
        panelPolicko14.zobrazZadnou();
        panelPolicko15.zobrazBilou();
        panelPolicko16.zobrazZadnou();
        panelPolicko17.zobrazBilou();
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPolicko1 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko2 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko3 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko4 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko5 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko6 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko7 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko8 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko9 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko10 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko11 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko12 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko13 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko14 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko15 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko16 = new ui.gui.komponenty.PanelPolicko();
        panelPolicko17 = new ui.gui.komponenty.PanelPolicko();

        setMaximumSize(new java.awt.Dimension(268, 272));
        setMinimumSize(new java.awt.Dimension(268, 272));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPolicko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(panelPolicko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPolicko2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPolicko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPolicko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPolicko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPolicko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPolicko3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPolicko1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPolicko3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPolicko5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPolicko2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPolicko12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPolicko7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelPolicko9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelPolicko13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelPolicko8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPolicko10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPolicko16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPolicko14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelPolicko15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelPolicko17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.gui.komponenty.PanelPolicko panelPolicko1;
    private ui.gui.komponenty.PanelPolicko panelPolicko10;
    private ui.gui.komponenty.PanelPolicko panelPolicko11;
    private ui.gui.komponenty.PanelPolicko panelPolicko12;
    private ui.gui.komponenty.PanelPolicko panelPolicko13;
    private ui.gui.komponenty.PanelPolicko panelPolicko14;
    private ui.gui.komponenty.PanelPolicko panelPolicko15;
    private ui.gui.komponenty.PanelPolicko panelPolicko16;
    private ui.gui.komponenty.PanelPolicko panelPolicko17;
    private ui.gui.komponenty.PanelPolicko panelPolicko2;
    private ui.gui.komponenty.PanelPolicko panelPolicko3;
    private ui.gui.komponenty.PanelPolicko panelPolicko4;
    private ui.gui.komponenty.PanelPolicko panelPolicko5;
    private ui.gui.komponenty.PanelPolicko panelPolicko6;
    private ui.gui.komponenty.PanelPolicko panelPolicko7;
    private ui.gui.komponenty.PanelPolicko panelPolicko8;
    private ui.gui.komponenty.PanelPolicko panelPolicko9;
    // End of variables declaration//GEN-END:variables

}
