/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPolicko.java
 *
 * Created on 15.1.2011, 15:31:44
 */
package ui.gui.komponenty;

import javax.swing.Icon;
import ui.alg.Policko;

/**
 *
 * @author notebook
 */
public final class PanelPolicko extends javax.swing.JPanel {

    protected Icon kulickaZlata = IkonyPolicka.getZlataKulicka();
    protected Icon kulickaCerna = IkonyPolicka.getCernaKulicka();
    protected Icon kulickaBila = IkonyPolicka.getBilaKulicka();

    private int cisloPolicka;

    /** Creates new form PanelPolicko */
    public PanelPolicko() {
        initComponents();        
    }    

     public void nastavHodnotuZPolicka(Policko policko){
        this.cisloPolicka = policko.getCisloPolicka();
        switch(policko.getBarva()){
            case -1: zobrazZadnou(); break;
            case 0: zobrazZlatou(); break;
            case 1: zobrazCernou(); break;
            case 2: zobrazBilou(); break;
        }
    }

    public void zobrazZlatou(){
        jLabelKulicka.setIcon(kulickaZlata);
    }
    
    public void zobrazCernou(){
        jLabelKulicka.setIcon(kulickaCerna);
    }
    public void zobrazBilou(){
        jLabelKulicka.setIcon(kulickaBila);
    }
    public void zobrazZadnou(){
        jLabelKulicka.setIcon(null);
    }

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelKulicka = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(30, 30));
        setMinimumSize(new java.awt.Dimension(30, 30));
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(jLabelKulicka, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelKulicka;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cisloPolicka
     */
    public int getCisloPolicka() {
        return cisloPolicka;
    }

    /**
     * @param cisloPolicka the cisloPolicka to set
     */
    public void setCisloPolicka(int cisloPolicka) {
        this.cisloPolicka = cisloPolicka;
    }
}
