/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlgoritmusJFrame.java
 *
 * Created on 22.2.2011, 20:47:05
 */
package ui.aplikace;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import ui.alg.Algortimus;
import ui.alg.StavHry;
import ui.alg.udalosti.CheckpointEvent;
import ui.alg.udalosti.CheckpointEventListener;
import ui.alg.udalosti.VypocetHotovEvent;
import ui.alg.udalosti.VypocetHotovEventListener;

/**
 *
 * @author tomas
 */
public class AlgoritmusJFrame extends javax.swing.JDialog {

    Algortimus alg;

    /** Creates new form AlgoritmusJFrame */
    public AlgoritmusJFrame() {
        initComponents();
    }

    public AlgoritmusJFrame(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHra1 = new ui.gui.komponenty.PanelHra();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonZastav = new javax.swing.JButton();
        jButtonSpust = new javax.swing.JButton();
        jTextFieldUz = new javax.swing.JTextField();
        jTextFieldOt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonDalsi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldChAkt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUdalosti = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Algoritmus");
        setResizable(false);

        jLabel1.setText("Aktuální stav:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonZastav.setText("Zastav");
        jButtonZastav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZastavActionPerformed(evt);
            }
        });

        jButtonSpust.setText("Stusť");
        jButtonSpust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpustActionPerformed(evt);
            }
        });

        jTextFieldUz.setEditable(false);
        jTextFieldUz.setText("0");

        jTextFieldOt.setEditable(false);
        jTextFieldOt.setText("0");

        jLabel3.setText("Počet v uzavřených");

        jLabel4.setText("Dosažených checkpointů");

        jTextFieldCh.setEditable(false);
        jTextFieldCh.setText("0");

        jLabel2.setText("Počet v otevřených");

        jButtonDalsi.setText("Další stav");
        jButtonDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDalsiActionPerformed(evt);
            }
        });

        jLabel5.setText("Aktuální úroveň tahu");

        jTextFieldChAkt.setEditable(false);
        jTextFieldChAkt.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonZastav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldChAkt)
                    .addComponent(jButtonDalsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSpust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUz)
                    .addComponent(jTextFieldOt)
                    .addComponent(jTextFieldCh))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZastav)
                    .addComponent(jButtonSpust))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDalsi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChAkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jTextAreaUdalosti.setColumns(20);
        jTextAreaUdalosti.setEditable(false);
        jTextAreaUdalosti.setRows(5);
        jScrollPane1.setViewportView(jTextAreaUdalosti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(panelHra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZastavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZastavActionPerformed
        // TODO add your handling code here:
        alg.zastav(true);
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("H:mm:ss:SSS");
        jTextAreaUdalosti.append(sdf.format(cal.getTime()) + " Algoritmus zastaven\n");
        nastavHodnoty((StavHry) alg.getAktualniStav());
    }//GEN-LAST:event_jButtonZastavActionPerformed

    private void jButtonSpustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpustActionPerformed
        // TODO add your handling code here:        
        alg.zastav(false);
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("H:mm:ss:SSS");
        jTextAreaUdalosti.append(sdf.format(cal.getTime()) + " Algoritmus spušťen\n");
    }//GEN-LAST:event_jButtonSpustActionPerformed

    private void jButtonDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDalsiActionPerformed
        // TODO add your handling code here:
        alg.setDebug(true);
        nastavHodnoty((StavHry) alg.getAktualniStav());
    }//GEN-LAST:event_jButtonDalsiActionPerformed

    public Algortimus getAlg() {
        return alg;
    }

    public void setAlg(final Algortimus alg) {
        this.alg = alg;
        alg.addCheckPointListener(new CheckpointEventListener() {

            public void CheckpointEventOccurred(CheckpointEvent evt) {
                SimpleDateFormat sdf = new SimpleDateFormat("H:mm:ss:SSS");
                jTextAreaUdalosti.append(sdf.format(evt.getCas()) + " Dosažen checkpoint " + evt.getCislo() + ".\n");
            }
        });
        alg.addVypocetHotovListener(new VypocetHotovEventListener() {

            public void VypocetHotovEventOccurred(VypocetHotovEvent evt) {
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("H:mm:ss:SSS");
                jTextAreaUdalosti.append(sdf.format(cal.getTime()) + " Výpočet dokončen!\n");
                ;
                nastavHodnoty((StavHry) evt.getStav().getKonecnyStav());
                jButtonDalsi.setEnabled(false);
                jButtonSpust.setEnabled(false);
                jButtonZastav.setEnabled(false);
            }
        });
    }

    private void nastavHodnoty(StavHry stav) {
        jTextFieldCh.setText(Integer.toString(alg.getPocetCheckPointu()));
        jTextFieldOt.setText(Integer.toString(alg.getPocetOtevrenych()));
        jTextFieldUz.setText(Integer.toString(alg.getPocetUzavrenych()));
        jTextFieldChAkt.setText(Integer.toString(stav.getUroven()));
        panelHra1.nastavPanelZeHry(stav.getValue());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDalsi;
    private javax.swing.JButton jButtonSpust;
    private javax.swing.JButton jButtonZastav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaUdalosti;
    private javax.swing.JTextField jTextFieldCh;
    private javax.swing.JTextField jTextFieldChAkt;
    private javax.swing.JTextField jTextFieldOt;
    private javax.swing.JTextField jTextFieldUz;
    private ui.gui.komponenty.PanelHra panelHra1;
    // End of variables declaration//GEN-END:variables
}
