/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelHra.java
 *
 * Created on 19.10.2010, 10:48:02
 */

package ui.test.komponenty;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author notebook
 */
public class PanelHra extends JPanel {

    /** Creates new form PanelHra */
    private Integer[] data;
    private List<JLabel> labels;

    public PanelHra() {
        initComponents();
        vytvorListLabelu();
    }

    private void vytvorListLabelu(){
        labels = new ArrayList<JLabel>();
        labels.add(jLabel1);
        labels.add(jLabel2);
        labels.add(jLabel3);
        labels.add(jLabel4);
        labels.add(jLabel5);
        labels.add(jLabel6);
        labels.add(jLabel7);
        labels.add(jLabel8);
        labels.add(jLabel9);
        labels.add(jLabel10);
    }

    private void setLabels(){
        Iterator<JLabel> iterator = labels.iterator();
        int i = 0;
        while (iterator.hasNext()) {
            JLabel jLabel = iterator.next();
            if(data[i] == 0){
                jLabel.setForeground(Color.red);
            } else {
                jLabel.setForeground(Color.black);
            }
            jLabel.setText(Integer.toString(data[i]));
            i++;
        }
    }

     public Integer[] getData() {
        return data;
    }

    public void setData(Integer[] data) {
        this.data = data;
        setLabels();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("jLabel1");
        jLabel4.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("jLabel1");
        jLabel5.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("jLabel1");
        jLabel6.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("jLabel1");
        jLabel7.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("jLabel1");
        jLabel8.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(jLabel8, gridBagConstraints);

        jLabel9.setText("jLabel1");
        jLabel9.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(jLabel9, gridBagConstraints);

        jLabel10.setText("jLabel1");
        jLabel10.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        add(jLabel10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
