/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormAlg.java
 *
 * Created on 3.11.2010, 17:53:27
 */
package ui.test.uialgoritmusv2;

import ui.alg.Algortimus;
import ui.alg.Stav;
import ui.alg.VyslednyStav;
import ui.test.komponenty.PanelHra;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author notebook
 */
public class FormAlg extends javax.swing.JFrame {

    private Hra pocatecni;
    VyslednyStav<Stav> koncovyStav;
    int aktKrok = 0;

    /** Creates new form FormAlg */
    public FormAlg() {
        initComponents();
        Hra pocatecni = new Hra();
        Integer[] pole = new Integer[10];
        for (int i = 0; i < 10; i++) {
            pole[i] = i + 1;
        }
        pole[9] = 0;
        pocatecni.setValue(pole);
        panelHraPocatecni.setData(pole);
        naplNasledujiciStavy(pocatecni);
        this.pocatecni = pocatecni;
        jButtonDalsi.setEnabled(false);
    }

    private void naplNasledujiciStavy(Hra stav) {
        jPanelNaslStavy.removeAll();
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Iterator<Stav<Integer[]>> iterator = stav.getNasledujiStavy().iterator();
        int i = 0;
        while (iterator.hasNext()) {
            PanelHra panelHra = new PanelHra();
            panelHra.setData(iterator.next().getValue());
            gridBagConstraints.gridx = i;
            i++;
            if (i == stav.getNasledujiStavy().size()) {
                gridBagConstraints.weightx = 1.0;
            }
            jPanelNaslStavy.add(panelHra, gridBagConstraints);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelPocStav = new javax.swing.JLabel();
        panelHraPocatecni = new ui.test.komponenty.PanelHra();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelNaslStavy = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelKoncovyStav = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldKroky = new javax.swing.JTextField();
        jTextFieldAlgKroky = new javax.swing.JTextField();
        panelHraKonec = new ui.test.komponenty.PanelHra();
        jPanel4 = new javax.swing.JPanel();
        jButtonVygeberuj = new javax.swing.JButton();
        jButtonVypocitej = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonDalsi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPocKroku = new javax.swing.JTextField();
        jTextFieldAktKroku = new javax.swing.JTextField();
        panelHraKroky = new ui.test.komponenty.PanelHra();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(75, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelPocStav.setText("Počáteční stav:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(jLabelPocStav, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(panelHraPocatecni, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 117));
        jPanel2.setMinimumSize(new java.awt.Dimension(399, 117));
        jPanel2.setPreferredSize(new java.awt.Dimension(312, 112));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Další možné stavy:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanelNaslStavy.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanelNaslStavy, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelKoncovyStav.setText("Koncový stav:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(jLabelKoncovyStav, gridBagConstraints);

        jLabel2.setText("Počet kroků: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Počet kroků algoritmu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 0, 5);
        jPanel3.add(jLabel3, gridBagConstraints);

        jTextFieldKroky.setEditable(false);
        jTextFieldKroky.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextFieldKroky.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextFieldKroky.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(jTextFieldKroky, gridBagConstraints);

        jTextFieldAlgKroky.setEditable(false);
        jTextFieldAlgKroky.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextFieldAlgKroky.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextFieldAlgKroky.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(jTextFieldAlgKroky, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(panelHraKonec, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonVygeberuj.setText("Vygeneruj");
        jButtonVygeberuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVygeberujActionPerformed(evt);
            }
        });

        jButtonVypocitej.setText("Vypočítej");
        jButtonVypocitej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVypocitejActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonDalsi.setText("Další");
        jButtonDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDalsiActionPerformed(evt);
            }
        });

        jLabel4.setText("Počet kroků:");

        jLabel5.setText("Aktuální krok:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPocKroku)
                            .addComponent(jTextFieldAktKroku, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDalsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelHraKroky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPocKroku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAktKroku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHraKroky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDalsi))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonVypocitej, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVygeberuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVygeberuj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVypocitej)
                .addGap(22, 22, 22)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVygeberujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVygeberujActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> pokus = new ArrayList<Integer>();
        for (int i = 0; i < 10; i++) {
            pokus.add(pocatecni.getValue()[i]);
        }
        Collections.shuffle(pokus);
        Integer[] vysl = new Integer[10];
//        for (int i = 0; i < 10; i++) {
//            vysl[i] =  pokus.get(i);
//        }
        for (int j = 0, i = 0; i < 10; i++) {
            if (pokus.get(i) != 9) {
                vysl[j] = pokus.get(i);
                j++;
            }
        }
        vysl[9] = 9;

        pocatecni.setValue(vysl);
        panelHraPocatecni.setData(pocatecni.getValue());
        naplNasledujiciStavy(pocatecni);
    }//GEN-LAST:event_jButtonVygeberujActionPerformed

    private void jButtonVypocitejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVypocitejActionPerformed
        // TODO add your handling code here:
        Integer[] pole = new Integer[10];
        for (int i = 0; i < 9; i++) {
            pole[i] = i + 1;
        }
        pole[9] = 0;
        Hra koncovy = new Hra(pole, 0, null);
        Algortimus alg = new Algortimus(pocatecni, koncovy);
        koncovyStav = alg.spust();
        if (koncovyStav == null) {
            JOptionPane.showMessageDialog(this, "Nemá řešení");
        } else {
            panelHraKonec.setData((Integer[]) koncovyStav.getKonecnyStav().getValue());
            jTextFieldAlgKroky.setText(Integer.toString(koncovyStav.getPocetKrokuCelkem()));
            jTextFieldKroky.setText(Integer.toString(koncovyStav.getPocetKroku()));
            jTextFieldAktKroku.setText(Integer.toString(koncovyStav.getPocetKroku()));
            panelHraKroky.setData((Integer[]) koncovyStav.getPosloupnostKroku().get(koncovyStav.getPosloupnostKroku().size() - 1).getValue());
            aktKrok = 0;
            jTextFieldPocKroku.setText("0");
            jButtonDalsi.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonVypocitejActionPerformed

    private void jButtonDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDalsiActionPerformed
        // TODO add your handling code here:
        aktKrok++;
        panelHraKroky.setData((Integer[]) koncovyStav.getPosloupnostKroku().get(
                koncovyStav.getPosloupnostKroku().size() - aktKrok - 1).getValue());
        jTextFieldPocKroku.setText(Integer.toString(aktKrok));
        if(aktKrok == koncovyStav.getPocetKroku()){
             jButtonDalsi.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonDalsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormAlg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDalsi;
    private javax.swing.JButton jButtonVygeberuj;
    private javax.swing.JButton jButtonVypocitej;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelKoncovyStav;
    private javax.swing.JLabel jLabelPocStav;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelNaslStavy;
    private javax.swing.JTextField jTextFieldAktKroku;
    private javax.swing.JTextField jTextFieldAlgKroky;
    private javax.swing.JTextField jTextFieldKroky;
    private javax.swing.JTextField jTextFieldPocKroku;
    private ui.test.komponenty.PanelHra panelHraKonec;
    private ui.test.komponenty.PanelHra panelHraKroky;
    private ui.test.komponenty.PanelHra panelHraPocatecni;
    // End of variables declaration//GEN-END:variables
}
